name: Build Python (arm64-v8a)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/python-build-reusable.yml
    with:
      termux_arch: aarch64
      android_abi: arm64-v8a
    secrets: inherit
